export const SYSTEM_VERSION = "2.0.0-Foundation";
export const SESSION_COOKIE_NAME = "hms_session";
export const LOCKOUT_ATTEMPTS = 5;
export const LOCKOUT_TIME_MINUTES = 15;
export const PASSWORD_EXPIRY_DAYS = 90;

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  PASSWORD_EXPIRED: "PASSWORD_EXPIRED",
};
