import crypto from "crypto";
import { SettingsService } from "./settings-service";

export interface LicenseData {
  expiryDate: string; // ISO String (e.g. 2026-12-31)
  registeredHospital: string;
  registeredOwner: string;
  version: string;
}

export interface LicenseValidator {
  verify(licenseKey: string, licenseData: LicenseData): boolean;
}

const LICENSE_SALT = "HMS_V2_PROD_READY_SECRET_SALT_2026";

/**
 * SymmetricHashLicenseValidator
 * Validates a license key generated by hashing key properties with a secret salt.
 * Product Key pattern: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
 */
export class SymmetricHashLicenseValidator implements LicenseValidator {
  verify(licenseKey: string, licenseData: LicenseData): boolean {
    const dataToSign = `${licenseData.registeredHospital.trim()}|${licenseData.registeredOwner.trim()}|${licenseData.expiryDate}|${licenseData.version.trim()}`;
    const hash = crypto.createHash("sha256").update(dataToSign + LICENSE_SALT).digest("hex").toUpperCase();
    
    // Format hash as standard activation key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
    const segments = [
      hash.substring(0, 5),
      hash.substring(5, 10),
      hash.substring(10, 15),
      hash.substring(15, 20),
      hash.substring(20, 25)
    ];
    const expectedKey = segments.join("-");
    
    return licenseKey.trim().toUpperCase() === expectedKey;
  }
}

/**
 * LicenseService
 * Manages hospital license validation, key updates, and status checks.
 * Uses a swappable validator instance (defaults to SymmetricHashLicenseValidator).
 */
export class LicenseService {
  private static validator: LicenseValidator = new SymmetricHashLicenseValidator();

  /**
   * Allows swapping the validator engine (e.g. to public/private RSA validator) without changing app code
   */
  static setValidator(customValidator: LicenseValidator) {
    this.validator = customValidator;
  }

  /**
   * Validates a license key and data payload
   */
  static validate(licenseKey: string, licenseData: LicenseData): boolean {
    return this.validator.verify(licenseKey, licenseData);
  }

  /**
   * Retrieves active license state and calculates remaining days.
   */
  static async getLicenseStatus() {
    const key = await SettingsService.getSetting("license_key") as string;
    const rawData = await SettingsService.getSetting("license_data") as LicenseData | null;
    const blockOnExpiry = await SettingsService.getSetting("maintenance_block_on_expiry") as boolean;

    if (!key || !rawData) {
      return {
        isValid: false,
        daysRemaining: 0,
        registeredHospital: "Unregistered",
        registeredOwner: "None",
        expiryDate: null,
        version: "N/A",
        isExpired: true,
        blockOnExpiry
      };
    }

    const isValid = this.validate(key, rawData);
    const expiry = new Date(rawData.expiryDate);
    const now = new Date();
    
    // Calculate days remaining
    const diffTime = expiry.getTime() - now.getTime();
    const daysRemaining = Math.max(0, Math.ceil(diffTime / (1000 * 60 * 60 * 24)));
    const isExpired = diffTime <= 0 || !isValid;

    return {
      isValid,
      daysRemaining,
      registeredHospital: rawData.registeredHospital,
      registeredOwner: rawData.registeredOwner,
      expiryDate: rawData.expiryDate,
      version: rawData.version,
      isExpired,
      blockOnExpiry
    };
  }

  /**
   * Helper to generate a valid activation key for testing or database setup
   */
  static generateTestKey(data: LicenseData): string {
    const dataToSign = `${data.registeredHospital.trim()}|${data.registeredOwner.trim()}|${data.expiryDate}|${data.version.trim()}`;
    const hash = crypto.createHash("sha256").update(dataToSign + LICENSE_SALT).digest("hex").toUpperCase();
    return [
      hash.substring(0, 5),
      hash.substring(5, 10),
      hash.substring(10, 15),
      hash.substring(15, 20),
      hash.substring(20, 25)
    ].join("-");
  }
}
